<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-3NLNO6U" failures="3" tests="14" name="cucumberTestRunner.TestRunner" time="147.771" errors="0" timestamp="2021-02-01T18:36:49 CST" skipped="0">
  <testcase classname="cucumberTestRunner.TestRunner" name="runScenario" time="10.276"/>
  <system-out/>
  <testcase classname="cucumberTestRunner.TestRunner" name="runScenario" time="10.646"/>
  <system-out/>
  <testcase classname="cucumberTestRunner.TestRunner" name="runScenario" time="10.792"/>
  <system-out/>
  <testcase classname="cucumberTestRunner.TestRunner" name="runScenario" time="10.581"/>
  <system-out/>
  <testcase classname="cucumberTestRunner.TestRunner" name="runScenario" time="10.149"/>
  <system-out/>
  <testcase classname="cucumberTestRunner.TestRunner" name="runScenario" time="11.352"/>
  <system-out/>
  <testcase classname="cucumberTestRunner.TestRunner" name="runScenario" time="10.731"/>
  <system-out/>
  <testcase classname="cucumberTestRunner.TestRunner" name="runScenario" time="10.818">
    <failure message="expected [1095.1300048828125] but found [1129.3900146484375]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [1095.1300048828125] but found [1129.3900146484375]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:671)
at org.testng.Assert.assertEquals(Assert.java:684)
at cucumberStepDefine.StepDefine.verify_that_converted_total_amount_with_avg_sell_and_percentage_price(StepDefine.java:51)
at ✽.Verify that converted total Amount with Avg Sell and Percentage 3 price(file:///D:/Selenium/Currency/src/test/java/features/currencyConv.feature:28)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="cucumberTestRunner.TestRunner" name="runScenario" time="9.899"/>
  <system-out/>
  <testcase classname="cucumberTestRunner.TestRunner" name="runScenario" time="11.322">
    <failure message="expected [960.0] but found [1000.0]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [960.0] but found [1000.0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:671)
at org.testng.Assert.assertEquals(Assert.java:684)
at cucumberStepDefine.StepDefine.verify_that_converted_total_amount_with_avg_sell_and_percentage_price(StepDefine.java:51)
at ✽.Verify that converted total Amount with Avg Sell and Percentage 4 price(file:///D:/Selenium/Currency/src/test/java/features/currencyConv.feature:28)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="cucumberTestRunner.TestRunner" name="runScenario" time="9.669">
    <failure message="expected [1129.0] but found [1129.3900146484375]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [1129.0] but found [1129.3900146484375]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:671)
at org.testng.Assert.assertEquals(Assert.java:684)
at cucumberStepDefine.StepDefine.verify_that_converted_total_amount_with_avg_sell_price(StepDefine.java:43)
at ✽.Verify that converted total Amount with Avg Sell price(file:///D:/Selenium/Currency/src/test/java/features/currencyConv.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="cucumberTestRunner.TestRunner" name="runScenario" time="10.603"/>
  <system-out/>
  <testcase classname="cucumberTestRunner.TestRunner" name="runScenario" time="10.444"/>
  <system-out/>
  <testcase classname="cucumberTestRunner.TestRunner" name="runScenario" time="10.489"/>
  <system-out/>
</testsuite> <!-- cucumberTestRunner.TestRunner -->
